name: Scheduled Jobs

on:
  schedule:
    - cron: '0 15 * * *'  # 한국 시간 기준 자정마다 실행됩니다.
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: github_manager

      - name: Add date and push
        run: |
          cd github_manager
          date >> date.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Inject Date"
          git push
